#!/usr/bin/env python

from datetime import datetime
import os
import numpy as np
from myUtilitiesModule import getPlotfileNumberArray, getMesh_1d, getFieldData

import globalVariables as gv

def getDensityDecades(plotfileDirectory, ID, dirSuffix):

    filename = gv.dataDirectory + 'tovStar/' \
                 + '{:}{:}_CentralDensityVersusTime.dat'.format(ID, dirSuffix)

    ow = True
    if (os.path.isfile(filename)):
        ow = input('File {:} exists. Overwrite? (y/N): '.format(filename))
        if (ow != 'y'):
            ow = False

    if (ow):

        print('\n  Generating {:}'.format(filename))

        plotfileBaseName = ID + '.plt'

        plotfileDirectory += ID + dirSuffix + '/'

        plotfileNumberArray \
          = getPlotfileNumberArray \
              (plotfileDirectory,\
               plotfileBaseName)

        SS = plotfileNumberArray[::1]

        nSS = SS.shape[0]

        time    = np.empty(nSS)
        density = np.empty(nSS)

        for iSS in range(nSS):

            if (iSS % 10 == 0):
              print('  {:}/{:}'.format(iSS, nSS))

            plotfileName = plotfileDirectory + plotfileBaseName + str(SS[iSS]).zfill(8)

            r, X2_C, X3_C, dr, dX2, dX3, xL, xH, t \
              = getMesh_1d(plotfileName, 'spherical', returnTime = True)

            rho    = getFieldData(plotfileName, 'PF_D'     , r, X2_C, X3_C)
            sqrtGm = getFieldData(plotfileName, 'GF_SqrtGm', r, X2_C, X3_C)

            vol  = 0.0
            rhoK = 0.0

            for iX1 in range(r.shape[0]):

                if (r[iX1] + 0.5 * dr[iX1] <= 1.0):

                    vol  += dr[iX1] * sqrtGm[iX1]
                    rhoK += dr[iX1] * sqrtGm[iX1] * rho[iX1]

            density[iSS] = rhoK / vol
            time   [iSS] = t

        header = '{:}\nGenerated by {:}\non {:}\ntime [ms], rhoC [g/cc]' \
                 .format(filename, __file__, datetime.today())

        np.savetxt(filename, np.vstack((time, density)), header = header)

        print('  Generated {:}'.format(filename))
    
if (__name__ == '__main__'):

    rootPathToData = gv.dataDirectory + 'tovStar/'

    ID        = ['StaticTOV_multiLevel', \
                 'StaticTOV_multiLevel', \
                 'StaticTOV_singleLevel', \
                 'StaticTOV_singleLevel', \
                 'StaticTOV_singleLevel']
    dirSuffix = ['_11', \
                 '_11_11', \
                 '_nX0032', \
                 '_nX0064', \
                 '_nX0128']

    for i in range(len(ID)):
        getDensityDecades(rootPathToData, ID[i], dirSuffix[i])

    import os
    os.system('rm -rf __pycache__')
