#!/usr/bin/env python3

from datetime import datetime
import os
import numpy as np
import matplotlib.pyplot as plt

import globalVariables as gv

def getFFT(ID, dirSuffix):

    filename = gv.dataDirectory + 'tovStar/' \
                 + '{:}{:}_CentralDensityVersusTime.dat'.format(ID, dirSuffix)

    t, rhoC = np.loadtxt(filename)
    
    t /= 1.0e3

    N  = t.shape[0]
    dt = np.mean(np.diff(t))
    
    fft_vals = np.fft.fft(rhoC)
    fft_freq = np.fft.fftfreq(N, d = dt)
    
    ind  = np.where(fft_freq > 0.0)[0]
    freq  = fft_freq[ind]
    power = (2.0 / N) * np.abs(fft_vals[ind])

    filename = gv.dataDirectory + 'tovStar/' \
                 + '{:}{:}_FFT.dat'.format(ID, dirSuffix)
    
    header = '{:}\nGenerated by {:}\non {:}\nfreq [Hz], power [g/cc]' \
             .format(filename, __file__, datetime.today())
    np.savetxt(filename, np.vstack((freq, power)), header = header)
    os.system('chmod 444 {:}'.format(filename))
    print('  Saved {:}'.format(filename))

if (__name__ == '__main__'):

    ID        = ['StaticTOV_multiLevel', \
                 'StaticTOV_multiLevel', \
                 'StaticTOV_singleLevel', \
                 'StaticTOV_singleLevel', \
                 'StaticTOV_singleLevel']
    dirSuffix = ['_11', \
                 '_11_11', \
                 '_nX0032', \
                 '_nX0064', \
                 '_nX0128']

    for i in range(len(ID)):
        getFFT(ID[i], dirSuffix[i])

    import os
    os.system('rm -rf __pycache__')
