#!/usr/bin/env python3

from datetime import datetime
import numpy as np

import GlobalVariables.Settings as gvS
gvS.PlotDirectory = '../../thornadoHydroXCFC_MethodsPaper_Data/'

from Utilities.GetFrameData import GetFrameData
from Utilities.Files import GetFileNumberArray

# These values copied from processedData/DensityDecades<suffix>.dat
tb025 = 2.416e+02
tb050 = 2.416e+02
tb100 = 2.416e+02

tb     = [ tb025          , tb050          , tb100           ]
suffix = [ '_AMR_dt0.25km', '_AMR_dr0.50km', '_AMR_dr1.00km' ]

ID = 'AdiabaticCollapse_XCFC'
plotfileBaseName = ID + '.plt'

for s in range( len( suffix ) ) :

    plotfileDirectory \
      = gvS.PlotDirectory \
          + '{:}{:}/'.format( ID, suffix[s] )

    plotfileArray \
      = GetFileNumberArray \
          ( plotfileDirectory,\
            plotfileBaseName,\
            -1, -1, \
            1 )

    tmtb = np.empty( plotfileArray.shape[0], np.float64 )
    DC   = np.empty( plotfileArray.shape[0], np.float64 )
    TC   = np.empty( plotfileArray.shape[0], np.float64 )
    YC   = np.empty( plotfileArray.shape[0], np.float64 )
    SC   = np.empty( plotfileArray.shape[0], np.float64 )

    print( 'Generating Data for {:}'.format( suffix[s][1:] ) )

    for iSS in range( plotfileArray.shape[0] ):

        if ( iSS % 10 == 0 ) :
            print( '\r {:}/{:}' \
                   .format( iSS, plotfileArray.shape[0] ), end = '\r' )

        D, DataUnits, X1, X2, X3, dX1, dX2, dX3, Time \
          = GetFrameData \
              ( plotfileDirectory \
                  + plotfileBaseName \
                      + str( plotfileArray[iSS] ).zfill( 8 ), \
                'AMReX', \
                'PF_D', \
                SaveTime = True )
        DC[iSS] = D[0]

        T, DataUnits, X1, X2, X3, dX1, dX2, dX3, Time \
          = GetFrameData \
              ( plotfileDirectory \
                  + plotfileBaseName \
                      + str( plotfileArray[iSS] ).zfill( 8 ), \
                'AMReX', \
                'AF_T', \
                SaveTime = True )
        TC[iSS] = T[0]

        Y, DataUnits, X1, X2, X3, dX1, dX2, dX3, Time \
          = GetFrameData \
              ( plotfileDirectory \
                  + plotfileBaseName \
                      + str( plotfileArray[iSS] ).zfill( 8 ), \
                'AMReX', \
                'AF_Y3', \
                SaveTime = True )
        YC[iSS] = Y[0]

        S, DataUnits, X1, X2, X3, dX1, dX2, dX3, Time \
          = GetFrameData \
              ( plotfileDirectory \
                  + plotfileBaseName \
                      + str( plotfileArray[iSS] ).zfill( 8 ), \
                'AMReX', \
                'AF_S', \
                SaveTime = True )
        SC[iSS] = S[0]

        tmtb[iSS] = Time - tb[s]

    print()

    header \
      = 'Generated by {:}\non {:}\nt - tb [ms], DC [g/cm^3], TC [K], YC, SC [kB/baryon]' \
        .format( __file__, datetime.today() )
    filename \
      = 'processedData/CentralValues{:}.dat'.format( suffix[s] )
    np.savetxt( filename, np.vstack( ( tmtb, DC, TC, YC, SC ) ), \
                header = header )
