#!/usr/bin/env python3

from datetime import datetime
import numpy as np

import GlobalVariables.Settings as gvS
gvS.PlotDirectory = '../../thornadoHydroXCFC_MethodsPaper_Data/'

from Utilities.GetFrameData import GetFrameData
from Utilities.Files import GetFileNumberArray

# These values copied from processedData/DensityDecades<suffix>.dat
tb025 = 2.416e+02
tb050 = 2.416e+02
tb100 = 2.416e+02
tb     = [ tb025          , tb050          , tb100           ]
suffix = [ '_AMR_dr0.25km', '_AMR_dr0.50km', '_AMR_dr1.00km' ]

tb050 =  2.417e+02
tb100 =  2.417e+02
tb     = [ tb050          , tb100 ]
suffix = [ '_Uni_dr0.50km', '_Uni_dr1.00km' ]

Fields = [ 'PF_D', 'AF_T', 'AF_Ye', 'AF_S' ]

ID = 'AdiabaticCollapse_XCFC'
plotfileBaseName = ID + '.plt'

for s in range( len( suffix ) ) :

    plotfileDirectory \
      = gvS.PlotDirectory \
          + '{:}{:}/'.format( ID, suffix[s] )

    plotfileArray \
      = GetFileNumberArray \
          ( plotfileDirectory,\
            plotfileBaseName,\
            -1, -1, \
            1 )

    tmtb = np.empty( plotfileArray.shape[0], np.float64 )
    qC   = np.empty( (len(Fields),plotfileArray.shape[0]), np.float64 )

    print( 'Generating Data for {:}'.format( suffix[s][1:] ) )

    for iSS in range( plotfileArray.shape[0] ):

        if ( iSS % 10 == 0 ) :
            print( '\r {:}/{:}' \
                   .format( iSS, plotfileArray.shape[0] ), end = '\r' )

        for i in range( len( Fields ) ):

            Data, DataUnits, X1, X2, X3, dX1, dX2, dX3, Time \
              = GetFrameData \
                  ( plotfileDirectory \
                      + plotfileBaseName \
                          + str( plotfileArray[iSS] ).zfill( 8 ), \
                    'AMReX', \
                    Fields[i], \
                    SaveTime = True )
            qC[i,iSS] = Data[0]

            tmtb[iSS] = Time - tb[s] # Hack

    print()

    header \
      = 'Generated by {:}\non {:}\ntb = {:} ms\nt - tb [ms], DC [g/cm^3], TC [K], YC, SC [kB/baryon]' \
        .format( __file__, datetime.today(), tb[s] )
    filename \
      = 'processedData/CentralValues{:}.dat'.format( suffix[s] )
    np.savetxt( filename, np.vstack( ( tmtb, qC[0], qC[1], qC[2], qC[3] ) ), \
                header = header )
    print( ' Saved {:}'.format( filename ) )
