#!/usr/bin/env python3

from datetime import datetime
import numpy as np

import GlobalVariables.Settings as gvS
gvS.PlotDirectory = '../../thornadoHydroXCFC_MethodsPaper_Data/'
gvS.Verbose = True
from GlobalVariables.Units   import SetSpaceTimeUnits

from Utilities.Files         import GetFileNumberArray
from Utilities.MakeDataArray import MakeProbelmDataDirectory

xSh = [ 1.0e2, 5.0e2, 1.0e3, 2.0e3, 4.0e3, 7.5e3 ]

def FindPostBounceShockLocations \
      ( plotfileDirectory, plotfileBaseName, dataDirectory, tb, suffix ):

    if( not plotfileDirectory[-1] == '/' ): plotfileDirectory += '/'
    if( not dataDirectory    [-1] == '/' ): dataDirectory     += '/'

    SSi = -1
    SSf = -1
    nSS = -1

    Field = 'PF_V1'

    SetSpaceTimeUnits( 'spherical', True )

    plotfileArray \
      = GetFileNumberArray \
          ( plotfileDirectory,\
            plotfileBaseName,\
            SSi, SSf, \
            1 )

    MakeProbelmDataDirectory \
      ( plotfileArray, \
        plotfileDirectory, \
        plotfileBaseName, \
        Field, \
        dataDirectory, \
        'AMReX' )

    if SSi == -1: SSi = 0
    if SSf == -1: SSf = plotfileArray.shape[0]-1
    if nSS == -1: nSS = plotfileArray.shape[0]

    PostBounceShockLocations = np.logspace( 10, 14, 5 )
    FoundLocation    \
      = np.array( [ False, False, False, False, False, False ], bool )

    ind = np.empty( (PostBounceShockLocations.shape[0]), np.int64 )
    t   = np.empty( (PostBounceShockLocations.shape[0]), np.int64 )

    rSh_lst = []
    t_lst   = []
    ss_lst  = []

    ii = 2

    for iSS in range( SSi, SSf ):

        if iSS % 10 == 0:
            print( '\r  {:d}/{:d}'.format( iSS, nSS ), end = '\r' )

        FileDirectory = dataDirectory + str( plotfileArray[iSS] ) + '/'

        TimeFile = FileDirectory + '{:}.dat'.format( 'Time' )
        X1File   = FileDirectory + '{:}.dat'.format( 'X1' )
        DataFile = FileDirectory + '{:}.dat'.format( Field )

        Time = np.loadtxt( TimeFile )
        X1_C = np.loadtxt( X1File   )
        Data = np.loadtxt( DataFile )

        if Time < tb: continue

        gradient      = 0.0
        shockGradient = 0.0
        shockTime     = 0.0
        xS            = 0.0
        sS            = 0
        for i in range( ii, Data.shape[0]-ii ):

            if X1_C[i] < 5.0e1 or X1_C[i] > 7.9e3: continue

            gradient \
              = np.abs( ( Data[i+ii] - Data[i] ) \
                         / ( ii * ( X1_C[i+ii] - X1_C[i] ) ) )

            if( gradient > shockGradient ):
                shockGradient = gradient
                shockTime     = Time
                xS            = X1_C[i]
                sS            = i

        rSh_lst.append( xS )
        t_lst .append( shockTime )
        ss_lst .append( iSS )

    print()

    t   = np.array( t_lst )
    Rsh = np.array( rSh_lst )
    ss  = np.array( ss_lst )

    header = 'Generated by {:}\non {:}\ntb = {:.3e} ms\nt-tb [ms], iSS, Rsh [km]' \
             .format( __file__, datetime.today(), tb )
    filename = 'processedData/ShockRadiusVsTime{:}.dat'.format( suffix )
    np.savetxt( filename, \
                np.vstack( ( t-tb, ss, Rsh ) ), header = header )
    print( '\n  Generated {:}'.format( filename ) )

    iRsh = [ np.where( Rsh >= x )[0][0] for x in xSh ]
    N = len( iRsh )

    filename = 'processedData/ShockRadii{:}.dat'.format( suffix )
    with open( filename, 'w' ) as f:

        f.write( 'Generated by {:}\non {:}\n' \
             .format( __file__, datetime.today() ) )

        f.write( 'To be used with plotMultiPanel_PostBounce.py\n' )

        f.write( 'tb = {:.3e} ms\n'.format( tb ) )

        f.write( 'Rsh [km], t(Rsh)-tb [ms], iSS(Rsh)\n' )

        f.write( 'Rsh = np.array( [ ' )
        for i in range( N-1 ):
            f.write( '{:.3e}, '.format( np.float64( Rsh[iRsh[i]] ) ) )
        f.write( '{:3e} ], dtype = np.float64 ) # km' \
                 .format( np.float64( Rsh[iRsh[N-1]] ) ) )

        f.write( '\ntmtb = np.array( [ ' )
        for i in range( N-1 ):
            f.write( '{:3e}, '.format( np.float64( t[iRsh[i]]-tb ) ) )
        f.write( '{:3e} ], dtype = np.float64 ) # ms' \
                 .format( np.float64( t[iRsh[N-1]]-tb ) ) )

        f.write( '\nsnapshots = np.array( [ ' )
        for i in range( N-1 ):
            f.write( '{:d}, '.format( np.int64( ss[iRsh[i]] ) ) )
        f.write( '{:d} ], dtype = np.int64 )' \
                 .format( np.int64( ss[iRsh[N-1]] ) ) )

    print( '\n  Generated {:}'.format( filename ) )

if __name__ == '__main__':

    ID = 'AdiabaticCollapse_XCFC'

    # tb copied from processedData/DensityDecades<suffix>.dat
#    suffix = '_AMR_dr0.25km'; tb = 2.416e2
#    suffix = '_AMR_dr0.50km'; tb = 2.416e2
#    suffix = '_AMR_dr1.00km'; tb = 2.416e2
#    suffix = '_Uni_dr0.50km'; tb = 2.417e2
    suffix = '_Uni_dr1.00km'; tb = 2.417e2

    plotfileDirectory \
      = gvS.PlotDirectory \
          + 'AdiabaticCollapse_XCFC{:}/'.format( suffix )

    plotfileBaseName = ID + '.plt'

    dataDirectory = '.{:}{:}/'.format( ID, suffix )

    FindPostBounceShockLocations \
      ( plotfileDirectory, plotfileBaseName, dataDirectory, tb, suffix )

    import os
    os.system( 'rm -rf __pycache__' )
