#!/usr/bin/env bash

# Create file ${outfile} containing a list of plotfiles that:
# 1.) Are not corrupted
# 2.) Are not files that have been re-written

#suffix=_AMR_dr0.25km
suffix=_AMR_dr0.50km
#suffix=_AMR_dr1.00km
#suffix=_Uni_dr0.50km
#suffix=_Uni_dr1.00km

pltDir=/lump/data/adiabaticCollapse_XCFC/AdiabaticCollapse_XCFC${suffix}_all
pltroot=AdiabaticCollapse_XCFC.plt
outfile=processedData/validPlotfiles${suffix}.dat

echo "# Valid plotfiles and associated times." > ${outfile}
echo "# Generated by" ${PWD}/${0} "on" $(date) >> ${outfile}
echo "# AbsolutePathToPlotfile Time/ms"        >> ${outfile}

for plotfile in ${pltDir}/${pltroot}* ; do
  skip="no"
  if [[ ${plotfile} == *".old."* ]]; then skip="yes"; fi
  for lev in ${plotfile}/Level* ; do
    if ! test -f ${lev}/Cell_H; then
      skip="yes"
    fi
  done
  if [[ ${skip} == "no" ]]; then
    time=`cat ${plotfile}/Header | sed '65q;d'`
    echo ${plotfile} ${time} >> ${outfile}
  fi
  if [[ ${skip} == "yes" ]]; then
    echo Skipping ${plotfile}
  fi
done
