#!/usr/bin/env python3

from datetime import datetime
import numpy as np

import globalVariables as gv

from computeL1Error import computeL1error

nn = [ 2, 3 ]

pathToData = gv.dataDirectory + 'SineWaveAdvection/'
fileNameRoot = 'Advection1D_SineWaveX1'

filename = gv.paperDirectory + 'FluxCorrections_L1.tex'
with open( filename, 'w' ) as f:
    f.write( '% Filename: {:}\n'.format( filename.split( '/' )[-1] ) )
    f.write( '% Generated by {:}\n% on {:}\n' \
             .format( __file__, datetime.today() ) )
    f.write( '\\begin{deluxetable}{ccccc}[htb!]\n' )
    f.write( '  \\tablecaption{Effect of Flux Corrections}\n' )
    f.write( '  \\tablehead{                %\n' )
    f.write( '  \\colhead{$N$}              &\n' )
    f.write( '  \\colhead{$\\NK$}            &\n' )
    f.write( '  \\colhead{Mesh}             &\n' )
    f.write( '  \\colhead{Flux Corrections} &\n' )
    f.write( '  \\colhead{$E_{1}\\left[\\rho_{h}\\right]$} }\n' )
    f.write( '  \\startdata\n' )

for i in range( len( nn ) ):

    narr  = []
    nxarr = []
    L1arr = []
    garr  = []
    fcarr = []

    nN = nn[i]

    nXC = 32

    N, nX1, L1 = computeL1error(nN, nXC, 'Single', '')
    narr .append( N   )
    nxarr.append( nX1 )
    L1arr.append( L1  )
    garr .append( 'Single' )
    fcarr.append( 'N/A' )

    nXC = 128

    N, nX1, L1 = computeL1error(nN, nXC, 'Single', '')
    narr .append( N   )
    nxarr.append( nX1 )
    L1arr.append( L1  )
    garr .append( 'Single' )
    fcarr.append( 'N/A' )

    nXC = 32

    N, nX1, L1 = computeL1error(nN, nXC, 'Multi', '_FCF')
    narr .append( N   )
    nxarr.append( nX1 )
    L1arr.append( L1  )
    garr .append( 'Multi' )
    fcarr.append( 'No' )

    N, nX1, L1 = computeL1error(nN, nXC, 'Multi', '_FCT')
    narr .append( N   )
    nxarr.append( nX1 )
    L1arr.append( L1  )
    garr .append( 'Multi' )
    fcarr.append( 'Yes' )

    with open( filename, 'a' ) as f:
        for i in range( len( L1arr ) ):
            exponent = np.floor( np.log10( np.abs( L1arr[i] ) ) )
            f.write( '{:} & {:} & {:} & {:} & ${:.2f}\\times10^{{{:}}}$ \\\\\n' \
                     .format( narr[i], nxarr[i], garr[i], fcarr[i], \
                              L1arr[i] / 10**( exponent ), np.int64( exponent ) ) )


with open( filename, 'a' ) as f:
    f.write( '  \\enddata\n' )
    f.write( '  \\label{tab.CR}\n' )
    f.write( '  \\tablecomments{Effects of flux corrections on the accuracy\n' )
    f.write( 'of our numerical method.\n' )
    f.write( 'The first column is the number of DG nodes per element,\n' )
    f.write( 'the second column is the number of elements,\n' )
    f.write( 'the third column specifies whether or not the simulation used a single-\n' )
    f.write( 'or multi-level mesh,\n' )
    f.write( 'the fourth column specifies whether or not a multi-level mesh simulation\n' )
    f.write( 'applied flux corrections,\n' )
    f.write( 'and the fifth column denotes the error as defined in\n' )
    f.write( '\\myeqref{eq.Error}.}\n' )
    f.write( '\\end{deluxetable}\n' )
print( '\n  Saved {:}'.format( filename ) )

import os
os.system( 'rm -rf __pycache__ ' )
