#!/usr/bin/env python

from datetime import datetime
import numpy as np
from scipy.optimize import curve_fit

import matplotlib.pyplot as plt

import globalVariables as gv

from computeL1Error import computeL1error

NN = [ 1, 2, 3 ]
Grid = ['Single', 'Multi']
FC = ['', '_FCF', '_FCT']
NXC = [16, 32, 64, 128, 256, 512]

pathToData = gv.dataDirectory + 'SineWaveAdvection/convergence_rates/'
fileNameRoot = pathToData + 'Advection1D_SineWaveX1'

filename = gv.paperDirectory + 'FluxCorrections_L1.tex'
with open( filename, 'w' ) as f:
    f.write( '% Filename: {:}\n'.format( filename.split( '/' )[-1] ) )
    f.write( '% Generated by {:}\n% on {:}\n' \
             .format( __file__, datetime.today() ) )
    f.write( '\\begin{deluxetable}{cccc}[htb!]\n' )
    f.write( '  \\tablecaption{Convergence Rates}\n' )
    f.write( '  \\tablehead{                %\n' )
    f.write( '  \\colhead{$N$}              &\n' )
    f.write( '  \\colhead{Mesh}             &\n' )
    f.write( '  \\colhead{Flux Corrections} &\n' )
    f.write( '  \\colhead{$\\left|\\chi\\right|$} }\n' )
    f.write( '  \\startdata\n' )

def linear(x, m, b):
    return m * x + b

nnn = 9
data = np.empty((nnn, 2*len(NXC)))
lab = ['DG(0), Single', \
       'DG(1), Single', \
       'DG(2), Single', \
       'DG(0), Multi, Off', \
       'DG(1), Multi, Off' , \
       'DG(2), Multi, Off' , \
       'DG(0), Multi, On'  , \
       'DG(1), Multi, On'  , \
       'DG(2), Multi, On'  ]
ls = [ \
      '-x', \
      '-.x', \
      '--x', \
      '-s', \
      '-.s', \
      '--s', \
      '-^', \
      '-.^', \
      '--^' \
     ]

mm = -1
for j in range(len(Grid)):

    grid = Grid[j]

    for k in range(len(FC)):

        fc = FC[k]

        for i in range(len(NN)):
        
            nN = NN[i]

            if ((grid == 'Single') & (fc != '')): continue
            if ((grid == 'Multi' ) & (fc == '')): continue

            nDOF = []
            E1 = []

            mm += 1

            for l in range(len(NXC)):
    
                nXC = NXC[l]
    
                N, nX, L1 = computeL1error(nN, nXC, grid, fc, fileNameRoot)

                data[mm,l] = N*nX
                data[mm,len(NXC)+l] = L1

                nDOF.append(np.log10(N * nX))
                E1.append(np.log10(L1))

            popt, pcov = curve_fit(linear, nDOF, E1)

            m = popt[0]

            if (fc == ''):
                fcc = 'N/A'
            elif (fc == '_FCF'):
                fcc = 'Off'
            else:
                fcc = 'On'

            with open( filename, 'a' ) as f:
               f.write( '{:} & {:} & {:} & ${:.2f}$ \\\\\n' \
                        .format( nN, grid, fcc, np.abs(m) ) )

fig, ax = plt.subplots()

for mm in range(nnn):
    if (mm % 3 == 0):
        j = 0
    if (mm % 3 == 1):
        j = 1
    if (mm % 3 == 2):
        j = 2
    if (mm // 3 == 0):
        i = 0
    if (mm // 3 == 1):
        i = 1
    if (mm // 3 == 2):
        i = 2

    ax.loglog(data[mm,0:len(NXC)], data[mm,len(NXC):], \
              ls[mm], c = gv.color[j], label = lab[mm], fillstyle = 'none')

nDOF = np.array([20, 1000], np.float64)
dg0  = nDOF**(-1)
dg1  = nDOF**(-2)
dg2  = nDOF**(-3)
plt.plot(nDOF, dg0, gv.color[0])
plt.plot(nDOF, dg1, gv.color[1])
plt.plot(nDOF, dg2, gv.color[2])
ax.set_xlabel('nDOF')
ax.text(nDOF[0], 0.20 * dg0[0], r'$\propto \mathrm{nDOF}^{-1}$', c = gv.color[0], fontsize = 10)
ax.text(nDOF[0], 0.09 * dg1[0], r'$\propto \mathrm{nDOF}^{-2}$', c = gv.color[1], fontsize = 10)
ax.text(nDOF[0], 0.04 * dg2[0], r'$\propto \mathrm{nDOF}^{-3}$', c = gv.color[2], fontsize = 10)
ax.set_ylabel(r'$E_1$')
ax.legend(prop={'size':8})
#plt.show()
figname = gv.paperDirectory + 'Figures/fig.convergence_rates.pdf'
plt.savefig(figname, dpi = 300)
print('  Saved {:}'.format(figname))
plt.close()

with open( filename, 'a' ) as f:
    f.write( '  \\enddata\n' )
    f.write( '  \\label{tab.CR}\n' )
    f.write( '  \\tablecomments{Effect of flux corrections on the accuracy\n' )
    f.write( 'of our numerical method.\n' )
    f.write( 'The first column is the number of DG nodes per element,\n' )
    f.write( 'the second column specifies whether or not the simulation used a single-\n' )
    f.write( 'or multi-level mesh,\n' )
    f.write( 'the third column specifies whether or not a multi-level \n' )
    f.write( 'mesh simulation applied flux corrections,\n' )
    f.write( 'and the fourth column denotes the convergence rate.}\n' )
    f.write( '\\end{deluxetable}\n' )
print( '\n  Saved {:}'.format( filename ) )

import os
os.system( 'rm -rf __pycache__ ' )
