#!/usr/bin/env python3

from datetime import datetime
import os
import numpy as np
import yt
yt.funcs.mylog.setLevel(40) # Suppress yt warnings

from myUtilitiesModule import getPlotfileNumberArray
import globalVariables as gv

### Beginning of user input ###

# Specify name of problem
problemName = 'StandingAccretionShock_XCFC'

plotfileDirectory = gv.dataDirectory + 'sasi/'

# Specify plot file base name
plotfileNameRoot = problemName + '.plt'

### End of user input ###

plotfileNumberArray \
  = getPlotfileNumberArray \
      (plotfileDirectory, \
       plotfileNameRoot)
plotfileNumberArray = plotfileNumberArray[0:-1:1]
nSS = plotfileNumberArray.shape[0]

shockedVolume = np.zeros(nSS, np.float64)
shockRadius   = np.empty(nSS, np.float64)
time          = np.empty(nSS, np.float64)
pe = 1
for iSS in range(nSS):

    print('{:}/{:}'.format(iSS, nSS))

    ds = yt.load(plotfileDirectory + plotfileNameRoot \
                    + str(plotfileNumberArray[iSS]).zfill(8))
    
    time[iSS] = ds.current_time.to_ndarray()

    ad = ds.all_data()
    r      = ad['X1_C'].to_ndarray()
    theta  = ad['X2_C'].to_ndarray()
    dr     = ad['dX1' ].to_ndarray()
    dtheta = ad['dX2' ].to_ndarray()

    rho    = ad['PF_D'].to_ndarray()
    p      = ad['AF_P'].to_ndarray()
    sqrtGm = ad['GF_SqrtGm'].to_ndarray()
    psi    = ad['GF_Psi'].to_ndarray()

    entropy = p / rho**(4.0 / 3.0)

    for i in range(0, entropy.shape[0], pe):
        if(entropy[i] > 2.1e14):
            shockedVolume[iSS] += 2.0 * np.pi * sqrtGm[i] * dr[i] * dtheta[i]

shockRadius = (3.0 / (4.0 * np.pi) * shockedVolume)**(1.0 / 3.0)

filename = gv.dataDirectory + 'sasi/shockRadiusVersusTime.dat'
header = '{:}\nGenerated by {:}\non {:}\ntime [ms], rSh [km]' \
         .format(filename, __file__, datetime.today())

np.savetxt(filename, np.vstack((time, shockRadius)), header = header)
os.system('chmod 444 {:}'.format(filename))

print('  Generated {:}'.format(filename))

os.system('rm -rf __pycache__')
